version: "2.2"

services:
  petclinic:
    build:
      context: ./
      dockerfile: Dockerfile
      target: build
    ports:
      - 8080:8080
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres
